[tool.poetry]
name = "python-pkg-template"
version = "0.1.0" 
description= " "
authors = [" "]

[tool.poetry.dependencies]
python = "^3.6.9"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"